version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: passbot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  password-manager:
    build: .
    environment:
      DATABASE_URL: postgres://bot:password@db:5432/passbot?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db