CREATE USER bot123;
GRANT ALL PRIVILEGES ON DATABASE passbot TO bot123;
ALTER USER bot123 WITH PASSWORD 'password';
CREATE TABLE passwords (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  resource TEXT NOT NULL,
  password TEXT NOT NULL
);